import { createSlice } from "@reduxjs/toolkit";

const homeSlice = createSlice({
  name: "home",
  initialState: {
    url: {},
    genre: {},
  },
  reducers: {
    getConfig: (state, action) => {
      state.url = action.payload;
    },
    getGenre: (state, action) => {
      state.genre = action.payload;
    },
  },
});

//Action creators are generated by RTK under the hood and the naming is same as reducer function
export const { getConfig, getGenre } = homeSlice.actions;
export default homeSlice.reducer;
